/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"stm32f1xx.h"
#include "RccTimerConfig.h"
#include "adc.h"
#include "adc_interr.h"

volatile uint16_t a=0;
int main(void)
{
	//bật cấu hình clock
	config();
	//cấu hình ADC có chỉnh a0 a1 a4 thành analog
	ADC_Init();
	//bật ADC
	ADC_Enable();
	//Cấu hình và chạy ADC với channel 1
	ADC_Start(4);
	//Cấu hình interrup cho ADC1_2 , là channel 1 2 4 cũng vậy, chắc là phải analog đơn nhỉ?
	ADC_Interr();


	GPIOC->ODR &=~GPIO_ODR_ODR13;
    /* Loop forever */
	while(1){

		if(a==1){
			GPIOC->ODR |=GPIO_ODR_ODR13;

		}
		else{
			GPIOC->ODR &=~GPIO_ODR_ODR13;
		}
		ADC1->CR1 |=0X20;




	}
}

void ADC1_2_IRQHandler(){
	ADC1->CR1 &=~0X20;
	if(ADC_GetVal() >3500){
		a=1;
	}
	else{
		a=0;
	}


}


