/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"stm32f1xx.h"
#include "RccTimerConfig.h"
#include "adc.h"
#include "adc_interr.h"
#include "adc_watchdog.h"

volatile uint16_t a=0;
int main(void)
{
	//bật cấu hình clock
	config();
	//cấu hình ADC có chỉnh a0 a1 a4 thành analog
	ADC_Init();
	//bật ADC
	ADC_Enable();
	//Cấu hình và chạy ADC với channel 1
	ADC_Start(1);
	//Cấu hình interrup cho ADC1_2 , là channel 0 1 4 cũng vậy, chắc là phải analog đơn nhỉ?
//	ADC_Interr();
	//Cấu hình wachdog
	ADC_Wachdog();

	GPIOC->ODR &=~GPIO_ODR_ODR13;
    /* Loop forever */
	while(1){


		if(a==1){
			GPIOC->ODR |=GPIO_ODR_ODR13;
			delay_ms(1000);
			a=0;
			GPIOC->ODR &=~GPIO_ODR_ODR13;
		}



		ADC1->CR1 |=ADC_CR1_AWDIE;



	}
}

//void ADC1_2_IRQHandler(){
//	ADC1->CR1 &=~0X20;
//	if(ADC_GetVal() >3500){
//		a=1;
//	}
//	else{
//		a=0;
//	}
//
//}

// HÀM NGẮT CỦA WATCH DOG
void ADC1_2_IRQHandler(){
//tắt interrupt wachdog. nếu không nó sẽ nhảy vào hàm này liên tục,
//vì tốc độ đọc analog nhanh
ADC1->CR1 &=~ADC_CR1_AWDIE;
//xóa bit trạng thái watch đog
ADC1->SR &=~ ADC_SR_AWD;

a = 1;
}


