/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"stm32f1xx.h"
#include "RccTimerConfig.h"
#include "adc.h"
int main(void)
{
	uint16_t ADC_VAL =0;
	config();
	ADC_Init();
	ADC_Enable();
    /* Loop forever */
	while(1){
		ADC_Start(1);
		ADC_WaitForConv();
		ADC_VAL=ADC_GetVal();
		if(ADC_VAL<2000){
			GPIOC->ODR |=GPIO_ODR_ODR13;
		}
		else{
			GPIOC->ODR &=~GPIO_ODR_ODR13;
		}
	}
}
